name: 'create terraform workflow'

on:
  push:
    branches: ['terraform']
  workflow_dispatch: #this attribute will enable the manual run to the pipeline
   
# Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
defaults:
  run:
    shell: bash
env: 
  ROOT_PATH:  '${{github.workspace}}/terraform'
  ARM_CLIENT_ID: ${{secrets.AZURE_CLIENT_ID}}
  ARM_CLIENT_SECRET: ${{secrets.AZURE_CLIENT_SECRET}}
  ARM_SUBSCRIPTION_ID: ${{secrets.AZURE_SUBSCRIPTION_ID}}
  ARM_TENANT_ID: ${{secrets.AZURE_TENANT_ID}}
  

jobs:
  terraform_plan:
    name: 'terraform plan'
    runs-on: ubuntu-latest
    
    steps:
    - name: print path
      run: echo 'path ::${{ env.ROOT_PATH }}'
    - name: print files
      run: |
          ls

    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
  
    - name: terraform init
      run: terraform init
      working-directory: ${{env.ROOT_PATH}}

    - name: terraform Plan
      run: terraform plan 
      working-directory: ${{env.ROOT_PATH}}
      env: 
        ROOT_PATH: '${{github.workspace}}/terraform'
        ARM_CLIENT_ID: ${{secrets.AZURE_CLIENT_ID}}
        ARM_CLIENT_SECRET: ${{secrets.AZURE_CLIENT_SECRET}}
        ARM_SUBSCRIPTION_ID: ${{secrets.AZURE_SUBSCRIPTION_ID}}
        ARM_TENANT_ID: ${{secrets.AZURE_TENANT_ID}}

  terraform_apply:
    name: 'Terraform apply'
    needs: [terraform_plan]
    runs-on: ubuntu-latest
    env: 
      ROOT_PATH: '${{github.workspace}}/terraform'
      ARM_CLIENT_ID: ${{secrets.AZURE_CLIENT_ID}}
      ARM_CLIENT_SECRET: ${{secrets.AZURE_CLIENT_SECRET}}
      ARM_SUBSCRIPTION_ID: ${{secrets.AZURE_SUBSCRIPTION_ID}}
      ARM_TENANT_ID: ${{secrets.AZURE_TENANT_ID}}

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
  
    - name: Terraform Init
      run: terraform init
      working-directory: ${{ env.ROOT_PATH }}

    - name: Terraform Apply
      run: terraform apply -auto-approve
      working-directory: ${{ env.ROOT_PATH }}
